// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_pass_email.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
	email = $2,
	hashed_password = $3,
	updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password
`

type UpdateUserParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
